### ISSUE TITLE
Release under Open Source License

### ISSUE THREAD

**Issue by p-friedrich** [Stefan-Endres/tgo#3]
I want to use this module in one of my projects. Just to be clear in legal aspects: Would it be possible to release the code under a [LGPL](https://choosealicense.com/licenses/lgpl-3.0/) compatible license?

If you have any problems I can help you with, please feel free to tell me.

**Comment by alchemyst** [comment]
Our plan is to have this included in `scipy.optimize`, which is released under the BSD license. Would this be OK for you? Also, we have been making steady progress with the algorithm in a different (private) repository in preparation for a journal article release, so stay tuned.

**Comment by Stefan-Endres** [comment]
There have been several delays in getting the test suite up to standard for a PR to `scipy.optimize`, but in the mean time I see no reason why we can't release this code under a compatible MIT licence. Closed with 49f4418.
